name: Test

on:
  push:
    branches:
      - '*'
  
env:
  name: Alice

jobs:
  build_1:
    runs-on: "ubuntu-latest"
    env:
      name: Bob
    steps:
    - name: Run a simple one-line script
      run: echo "Hello $name"

  build_2:
    runs-on: "ubuntu-latest"
    steps:
    - name: Run a simple one-line script
      run: echo Hello $name

  dump:
    runs-on: ubuntu-latest
    steps:
    - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo Actor: ${{ github.actor }}
