name: howdy-world-example

on:
  push:

jobs:
  say-howdy:
    runs-on: ubuntu-latest

    steps:
    - name: Say Howdy Ya'all
      run: echo "Howdy World!"
    - name: Say steps here
      run: |
        echo "Step 1 ..."
        echo "Step 2 ..."
        echo "Step 3 ..."
    - name: Say Later
      run: echo "Later Gators!"
